### ISSUE TITLE
clearErrors not working.

### ISSUE THREAD

**Issue by martinhbramwell** [warehouseman/meteor-mantra-kickstarter#1]
clearErrors not working.

need to determine correct place lifecycle and how to do it.

**Comment by StorytellerCZ** [comment]
Just looking around. You put clearErrors in container in composer as a return. At least that how it worked on my Mantra project.

```javascript
return clearErrors;
```

**Comment by martinhbramwell** [comment]
Oh! Thank you.  I think that's all working and that I just forgot to close the issue.

Your input is hugely appreciated.  If you have some further insights about your installing, building, running experiences, please comment [here](https://forums.meteor.com/t/risen-from-the-ashes-meteor-mantra-kickstarter-refurb/32056).  It'll help raise the profile so that those who want it, have a chance to know it is actually here available.
