### ISSUE TITLE
'mmks_widget' is not in the npm registry

### ISSUE THREAD

**Issue by kurapikats** [warehouseman/meteor-mantra-kickstarter#3]
Hi,

I'm trying to install packages via:
$ meteor npm install
but I'm getting this error message:

> npm ERR! Darwin 15.6.0
> npm ERR! argv "/Users/onin/.nvm/versions/node/v6.9.1/bin/node" "/Users/onin/.nvm/versions/node/v6.9.1/bin/npm" "i"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.9
> npm ERR! code E404
> 
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/mmks_widget
> npm ERR! 404
> npm ERR! 404  'mmks_widget' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 It was specified as a dependency of 'meteor-mantra-kickstarter'
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/onin/projects/sandbox/mantra/meteor-mantra-kickstarter/npm-debug.log

I'm using OSX El Capitan
Meteor 1.4.2.3
node 6.9.1

TIA!

**Comment by martinhbramwell** [comment]
Hi, @kurapikats 

To help you, I need to know . . . did you follow the README.md ["Getting Started" instructions](https://github.com/warehouseman/meteor-mantra-kickstarter#getting-started) ??

In step 7, the script [./install_all.sh](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/install_all.sh#L13) runs the script [.scripts/installMeteorApp.sh](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.scripts/installMeteorApp.sh#L8) which runs [.pkgs/install_local_packages.sh](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/install_local_packages.sh). That script uses `npm link*` to [declare](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/install_local_packages.sh#L15) and [import](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/install_local_packages.sh#L30) any unpublished local packages. 

The script will save you many other tedious manual steps.  I wrote the scripts so as to avoid having to write long  error prone set up instructions.

Rgds,
Martin

* npm link -- [https://docs.npmjs.com/cli/link](https://docs.npmjs.com/cli/link)

**Comment by kurapikats** [comment]
nvm, it worked. My bad, I didn't look at the readme file I just assumed to use it like a normal meteor.

**Comment by martinhbramwell** [comment]
I'm glad you're moving forward!

If you encounter any other difficulties, definitely feel free to ask.
