### ISSUE TITLE
Missing obligatory mobile-settings in 

### ISSUE THREAD

**Issue by yourse1f-yourorg** [warehouseman/meteor-mantra-kickstarter#8]
# in .scripts/android/installAndBuildTools.sh

     -    echo -e "\nBuilding project : meteor build ${TARGET_DIRECTORY}         --server=${HOST_SERVER_URI};\n\n";
     -    meteor build ${TARGET_DIRECTORY}         --server=${HOST_SERVER_URI};
     +    echo -e "\nBuilding project : meteor build ${TARGET_DIRECTORY} --mobile-settings=settings.json --server=${HOST_SERVER_URI};\n\n";
     +    meteor build ${TARGET_DIRECTORY} --mobile-settings=settings.json --server=${HOST_SERVER_URI};

**Comment by martinhbramwell** [comment]
fixed
